Use Vagrant's Ruby else system Ruby else fail

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -42,13 +42,37 @@ VBoxManage storageattach ${NAME} \
 
 VBoxManage startvm ${NAME} --type gui
 
+setup_ruby() {
+    # handle errors in here
+    set +e
+
+    SOURCE=$(which vagrant)
+    if [ $? -eq 0 ]; then
+        while [ -h "$SOURCE" ] ; do SOURCE="$(readlink "$SOURCE")"; done
+        EMBEDDED_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )/../embedded"
+
+        unset RUBYOPT
+        RUBY_EXECUTABLE="${EMBEDDED_DIR}/bin/ruby"
+    else
+        RUBY_EXECUTABLE=$(which ruby)
+        if [ ! $? -eq 0 ]; then
+            echo "Cannot find Ruby (needed for kickstart file)"
+            exit 1
+        fi
+    fi
+
+    set -e
+}
+
 # This only really caters for the common case. If you have problems, please
 # discover your host's IP address and adjust accordingly.
 IP=`echo ${NATNET} | sed -nE 's/^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}).*/\1/p'`
 
+setup_ruby
+
 echo 'At the boot prompt, hit <TAB> and then type:'
 /bin/echo -n " ks=http://${IP}.3:"
-ruby httpd.rb ks.cfg
+${RUBY_EXECUTABLE} httpd.rb ks.cfg
 
 echo When finished:
 echo "./cleanup && vagrant package --base ${NAME} --output boxes/${NAME}-`date +%Y%m%d`.box"
